// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type programEnterState struct {
	_         structs.HostLayout
	Pid       uint32
	Tid       uint32
	Uid       uint32
	SyscallId uint32
	Ppid      uint32
	Pad       int32
	TsNsEnter uint64
	CgroupId  uint64
	Comm      [16]int8
	Args      [6]uint64
	DerefArgs [6]uint64
}

// loadProgram returns the embedded CollectionSpec for program.
func loadProgram() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProgramBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load program: %w", err)
	}

	return spec, err
}

// loadProgramObjects loads program and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*programObjects
//	*programPrograms
//	*programMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProgramObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProgram()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// programSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programSpecs struct {
	programProgramSpecs
	programMapSpecs
	programVariableSpecs
}

// programProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programProgramSpecs struct {
	CaptureSysEnter *ebpf.ProgramSpec `ebpf:"capture_sys_enter"`
	CaptureSysExit  *ebpf.ProgramSpec `ebpf:"capture_sys_exit"`
}

// programMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programMapSpecs struct {
	CgroupIdMap *ebpf.MapSpec `ebpf:"cgroup_id_map"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	Inflight    *ebpf.MapSpec `ebpf:"inflight"`
}

// programVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type programVariableSpecs struct {
	SyscallPtrArgs *ebpf.VariableSpec `ebpf:"syscall_ptr_args"`
}

// programObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programObjects struct {
	programPrograms
	programMaps
	programVariables
}

func (o *programObjects) Close() error {
	return _ProgramClose(
		&o.programPrograms,
		&o.programMaps,
	)
}

// programMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programMaps struct {
	CgroupIdMap *ebpf.Map `ebpf:"cgroup_id_map"`
	Events      *ebpf.Map `ebpf:"events"`
	Inflight    *ebpf.Map `ebpf:"inflight"`
}

func (m *programMaps) Close() error {
	return _ProgramClose(
		m.CgroupIdMap,
		m.Events,
		m.Inflight,
	)
}

// programVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programVariables struct {
	SyscallPtrArgs *ebpf.Variable `ebpf:"syscall_ptr_args"`
}

// programPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProgramObjects or ebpf.CollectionSpec.LoadAndAssign.
type programPrograms struct {
	CaptureSysEnter *ebpf.Program `ebpf:"capture_sys_enter"`
	CaptureSysExit  *ebpf.Program `ebpf:"capture_sys_exit"`
}

func (p *programPrograms) Close() error {
	return _ProgramClose(
		p.CaptureSysEnter,
		p.CaptureSysExit,
	)
}

func _ProgramClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed program_bpfel.o
var _ProgramBytes []byte
