package main

var syscallTable = make(map[int]string)

func initTable() {
	syscallTable = map[int]string{
		0:   "read",
		1:   "write",
		2:   "open",
		3:   "close",
		4:   "stat",
		5:   "fstat",
		6:   "lstat",
		7:   "poll",
		8:   "lseek",
		9:   "mmap",
		10:  "mprotect",
		11:  "munmap",
		12:  "brk",
		13:  "rt_sigaction",
		14:  "rt_sigprocmask",
		15:  "rt_sigreturn",
		16:  "ioctl",
		17:  "pread64",
		18:  "pwrite64",
		19:  "readv",
		20:  "writev",
		21:  "access",
		22:  "pipe",
		23:  "select",
		24:  "sched_yield",
		25:  "mremap",
		26:  "msync",
		27:  "mincore",
		28:  "madvise",
		29:  "shmget",
		30:  "shmat",
		31:  "shmctl",
		32:  "dup",
		33:  "dup2",
		34:  "pause",
		35:  "nanosleep",
		36:  "getitimer",
		37:  "alarm",
		38:  "setitimer",
		39:  "getpid",
		40:  "sendfile",
		41:  "socket",
		42:  "connect",
		43:  "accept",
		44:  "sendto",
		45:  "recvfrom",
		46:  "sendmsg",
		47:  "recvmsg",
		48:  "shutdown",
		49:  "bind",
		50:  "listen",
		51:  "getsockname",
		52:  "getpeername",
		53:  "socketpair",
		54:  "setsockopt",
		55:  "getsockopt",
		56:  "clone",
		57:  "fork",
		58:  "vfork",
		59:  "execve",
		60:  "exit",
		61:  "wait4",
		62:  "kill",
		63:  "uname",
		64:  "semget",
		65:  "semop",
		66:  "semctl",
		67:  "shmdt",
		68:  "msgget",
		69:  "msgsnd",
		70:  "msgrcv",
		71:  "msgctl",
		72:  "fcntl",
		73:  "flock",
		74:  "fsync",
		75:  "fdatasync",
		76:  "truncate",
		77:  "ftruncate",
		78:  "getdents",
		79:  "getcwd",
		80:  "chdir",
		81:  "fchdir",
		82:  "rename",
		83:  "mkdir",
		84:  "rmdir",
		85:  "creat",
		86:  "link",
		87:  "unlink",
		88:  "symlink",
		89:  "readlink",
		90:  "chmod",
		91:  "fchmod",
		92:  "chown",
		93:  "fchown",
		94:  "lchown",
		95:  "umask",
		96:  "gettimeofday",
		97:  "getrlimit",
		98:  "getrusage",
		99:  "sysinfo",
		100: "times",
		101: "ptrace",
		102: "getuid",
		103: "syslog",
		104: "getgid",
		105: "setuid",
		106: "setgid",
		107: "geteuid",
		108: "getegid",
		109: "setpgid",
		110: "getppid",
		111: "getpgrp",
		112: "setsid",
		113: "setreuid",
		114: "setregid",
		115: "getgroups",
		116: "setgroups",
		117: "setresuid",
		118: "getresuid",
		119: "setresgid",
		120: "getresgid",
		121: "getpgid",
		122: "setfsuid",
		123: "setfsgid",
		124: "getsid",
		125: "capget",
		126: "capset",
		127: "rt_sigpending",
		128: "rt_sigtimedwait",
		129: "rt_sigqueueinfo",
		130: "rt_sigsuspend",
		131: "sigaltstack",
		132: "utime",
		133: "mknod",
		134: "uselib",
		135: "personality",
		136: "ustat",
		137: "statfs",
		138: "fstatfs",
		139: "sysfs",
		140: "getpriority",
		141: "setpriority",
		142: "sched_setparam",
		143: "sched_getparam",
		144: "sched_setscheduler",
		145: "sched_getscheduler",
		146: "sched_get_priority_max",
		147: "sched_get_priority_min",
		148: "sched_rr_get_interval",
		149: "mlock",
		150: "munlock",
		151: "mlockall",
		152: "munlockall",
		153: "vhangup",
		154: "modify_ldt",
		155: "pivot_root",
		156: "_sysctl",
		157: "prctl",
		158: "arch_prctl",
		159: "adjtimex",
		160: "setrlimit",
		161: "chroot",
		162: "sync",
		163: "acct",
		164: "settimeofday",
		165: "mount",
		166: "umount2",
		167: "swapon",
		168: "swapoff",
		169: "reboot",
		170: "sethostname",
		171: "setdomainname",
		172: "iopl",
		173: "ioperm",
		174: "create_module",
		175: "init_module",
		176: "delete_module",
		177: "get_kernel_syms",
		178: "query_module",
		179: "quotactl",
		180: "nfsservctl",
		181: "getpmsg",
		182: "putpmsg",
		183: "afs_syscall",
		184: "tuxcall",
		185: "security",
		186: "gettid",
		187: "readahead",
		188: "setxattr",
		189: "lsetxattr",
		190: "fsetxattr",
		191: "getxattr",
		192: "lgetxattr",
		193: "fgetxattr",
		194: "listxattr",
		195: "llistxattr",
		196: "flistxattr",
		197: "removexattr",
		198: "lremovexattr",
		199: "fremovexattr",
		200: "tkill",
		201: "time",
		202: "futex",
		203: "sched_setaffinity",
		204: "sched_getaffinity",
		205: "set_thread_area",
		206: "io_setup",
		207: "io_destroy",
		208: "io_getevents",
		209: "io_submit",
		210: "io_cancel",
		211: "get_thread_area",
		212: "lookup_dcookie",
		213: "epoll_create",
		214: "epoll_ctl_old",
		215: "epoll_wait_old",
		216: "remap_file_pages",
		217: "getdents64",
		218: "set_tid_address",
		219: "restart_syscall",
		220: "semtimedop",
		221: "fadvise64",
		222: "timer_create",
		223: "timer_settime",
		224: "timer_gettime",
		225: "timer_getoverrun",
		226: "timer_delete",
		227: "clock_settime",
		228: "clock_gettime",
		229: "clock_getres",
		230: "clock_nanosleep",
		231: "exit_group",
		232: "epoll_wait",
		233: "epoll_ctl",
		234: "tgkill",
		235: "utimes",
		236: "vserver",
		237: "mbind",
		238: "set_mempolicy",
		239: "get_mempolicy",
		240: "mq_open",
		241: "mq_unlink",
		242: "mq_timedsend",
		243: "mq_timedreceive",
		244: "mq_notify",
		245: "mq_getsetattr",
		246: "kexec_load",
		247: "waitid",
		248: "add_key",
		249: "request_key",
		250: "keyctl",
		251: "ioprio_set",
		252: "ioprio_get",
		253: "inotify_init",
		254: "inotify_add_watch",
		255: "inotify_rm_watch",
		256: "migrate_pages",
		257: "openat",
		258: "mkdirat",
		259: "mknodat",
		260: "fchownat",
		261: "futimesat",
		262: "newfstatat",
		263: "unlinkat",
		264: "renameat",
		265: "linkat",
		266: "symlinkat",
		267: "readlinkat",
		268: "fchmodat",
		269: "faccessat",
		270: "pselect6",
		271: "ppoll",
		272: "unshare",
		273: "set_robust_list",
		274: "get_robust_list",
		275: "splice",
		276: "tee",
		277: "sync_file_range",
		278: "vmsplice",
		279: "move_pages",
		280: "utimensat",
		281: "epoll_pwait",
		282: "signalfd",
		283: "timerfd_create",
		284: "eventfd",
		285: "fallocate",
		286: "timerfd_settime",
		287: "timerfd_gettime",
		288: "accept4",
		289: "signalfd4",
		290: "eventfd2",
		291: "epoll_create1",
		292: "dup3",
		293: "pipe2",
		294: "inotify_init1",
		295: "preadv",
		296: "pwritev",
		297: "rt_tgsigqueueinfo",
		298: "perf_event_open",
		299: "recvmmsg",
		300: "fanotify_init",
		301: "fanotify_mark",
		302: "prlimit64",
		303: "name_to_handle_at",
		304: "open_by_handle_at",
		305: "clock_adjtime",
		306: "syncfs",
		307: "sendmmsg",
		308: "setns",
		309: "getcpu",
		310: "process_vm_readv",
		311: "process_vm_writev",
		312: "kcmp",
		313: "finit_module",
		314: "sched_setattr",
		315: "sched_getattr",
		316: "renameat2",
		317: "seccomp",
		318: "getrandom",
		319: "memfd_create",
		320: "kexec_file_load",
		321: "bpf",
		322: "execveat",
		323: "userfaultfd",
		324: "membarrier",
		325: "mlock2",
		326: "copy_file_range",
		327: "preadv2",
		328: "pwritev2",
		329: "pkey_mprotect",
		330: "pkey_alloc",
		331: "pkey_free",
		332: "statx",
		333: "io_pgetevents",
		334: "rseq",
		335: "uretprobe",
		336: "uprobe",
		424: "pidfd_send_signal",
		425: "io_uring_setup",
		426: "io_uring_enter",
		427: "io_uring_register",
		428: "open_tree",
		429: "move_mount",
		430: "fsopen",
		431: "fsconfig",
		432: "fsmount",
		433: "fspick",
		434: "pidfd_open",
		435: "clone3",
		436: "close_range",
		437: "openat2",
		438: "pidfd_getfd",
		439: "faccessat2",
		440: "process_madvise",
		441: "epoll_pwait2",
		442: "mount_setattr",
		443: "quotactl_fd",
		444: "landlock_create_ruleset",
		445: "landlock_add_rule",
		446: "landlock_restrict_self",
		447: "memfd_secret",
		448: "process_mrelease",
		449: "futex_waitv",
		450: "set_mempolicy_home_node",
		451: "cachestat",
		452: "fchmodat2",
		453: "map_shadow_stack",
		454: "futex_wake",
		455: "futex_wait",
		456: "futex_requeue",
		457: "statmount",
		458: "listmount",
		459: "lsm_get_self_attr",
		460: "lsm_set_self_attr",
		461: "lsm_list_modules",
		462: "mseal",
		463: "setxattrat",
		464: "getxattrat",
		465: "listxattrat",
		466: "removexattrat",
		467: "open_tree_attr",
		468: "file_getattr",
		469: "file_setattr",
		470: "listns",
		471: "rseq_slice_yield",
	}
}

var syscallFields = map[string][]string{
	"sched_get_priority_min": {
		"int policy",
	},
	"signalfd": {
		"int ufd",
		"sigset_t *user_mask",
		"size_t sizemask",
	},
	"timerfd_settime": {
		"int ufd",
		"int flags",
		"const struct __kernel_itimerspec *utmr",
		"struct __kernel_itimerspec *otmr",
	},
	"sethostname": {
		"char *name",
		"int len",
	},
	"mq_open": {
		"const char *u_name",
		"int oflag",
		"umode_t mode",
		"struct mq_attr *u_attr",
	},
	"mq_timedreceive": {
		"mqd_t mqdes",
		"char *u_msg_ptr",
		"size_t msg_len",
		"unsigned int *u_msg_prio",
		"const struct __kernel_timespec *u_abs_timeout",
	},
	"accept4": {
		"int fd",
		"struct sockaddr *upeer_sockaddr",
		"int *upeer_addrlen",
		"int flags",
	},
	"pipe2": {
		"int *fildes",
		"int flags",
	},
	"getrandom": {
		"char *ubuf",
		"size_t len",
		"unsigned int flags",
	},
	"umask": {
		"int mask",
	},
	"setpgid": {
		"pid_t pid",
		"pid_t pgid",
	},
	"futex": {
		"u32 *uaddr",
		"int op",
		"u32 val",
		"const struct __kernel_timespec *utime",
		"u32 *uaddr2",
		"u32 val3",
	},
	"tgkill": {
		"pid_t tgid",
		"pid_t pid",
		"int sig",
	},
	"set_mempolicy": {
		"int mode",
		"const unsigned long *nmask",
		"unsigned long maxnode",
	},
	"get_robust_list": {
		"int pid",
		"struct robust_list_head * *head_ptr",
		"size_t *len_ptr",
	},
	"pwrite64": {
		"unsigned int fd",
		"const char *buf",
		"size_t count",
		"loff_t pos",
	},
	"msgget": {
		"key_t key",
		"int msgflg",
	},
	"getgroups": {
		"int gidsetsize",
		"gid_t *grouplist",
	},
	"mlock": {
		"unsigned long start",
		"size_t len",
	},
	"vhangup": {},
	"clock_gettime": {
		"const clockid_t which_clock",
		"struct __kernel_timespec *tp",
	},
	"timerfd_gettime": {
		"int ufd",
		"struct __kernel_itimerspec *otmr",
	},
	"sendmsg": {
		"int fd",
		"struct user_msghdr *msg",
		"unsigned int flags",
	},
	"readlink": {
		"const char *path",
		"char *buf",
		"int bufsiz",
	},
	"kexec_load": {
		"unsigned long entry",
		"unsigned long nr_segments",
		"struct kexec_segment *segments",
		"unsigned long flags",
	},
	"tee": {
		"int fdin",
		"int fdout",
		"size_t len",
		"unsigned int flags",
	},
	"inotify_init1": {
		"int flags",
	},
	"userfaultfd": {
		"int flags",
	},
	"faccessat2": {
		"int dfd",
		"const char *filename",
		"int mode",
		"int flags",
	},
	"mprotect": {
		"unsigned long start",
		"size_t len",
		"unsigned long prot",
	},
	"io_destroy": {
		"aio_context_t ctx",
	},
	"set_tid_address": {
		"int *tidptr",
	},
	"name_to_handle_at": {
		"int dfd",
		"const char *name",
		"struct file_handle *handle",
		"void *mnt_id",
		"int flag",
	},
	"fsconfig": {
		"int fd",
		"unsigned int cmd",
		"int aux",
	},
	"dup": {
		"unsigned int fildes",
	},
	"semget": {
		"key_t key",
		"int nsems",
		"int semflg",
	},
	"unlink": {
		"const char *pathname",
	},
	"chmod": {
		"const char *filename",
		"umode_t mode",
	},
	"setresuid": {
		"uid_t ruid",
		"uid_t euid",
		"uid_t suid",
	},
	"getresuid": {
		"uid_t *ruidp",
		"uid_t *euidp",
		"uid_t *suidp",
	},
	"mount_setattr": {
		"int dfd",
		"const char *path",
		"unsigned int flags",
		"struct mount_attr *uattr",
		"size_t usize",
	},
	"file_setattr": {
		"int dfd",
		"const char *filename",
		"struct file_attr *ufattr",
		"size_t usize",
		"unsigned int at_flags",
	},
	"chdir": {
		"const char *filename",
	},
	"fallocate": {
		"int fd",
		"int mode",
		"loff_t offset",
		"loff_t len",
	},
	"process_madvise": {
		"int pidfd",
		"const struct iovec *vec",
		"size_t vlen",
		"int behavior",
		"unsigned int flags",
	},
	"pause": {},
	"fadvise64": {
		"int fd",
		"loff_t offset",
		"size_t len",
		"int advice",
	},
	"newfstatat": {
		"int dfd",
		"const char *filename",
		"struct stat *statbuf",
		"int flag",
	},
	"dup3": {
		"unsigned int oldfd",
		"unsigned int newfd",
		"int flags",
	},
	"io_pgetevents": {
		"aio_context_t ctx_id",
		"long min_nr",
		"long nr",
		"struct io_event *events",
		"struct __kernel_timespec *timeout",
		"const struct __aio_sigset *usig",
	},
	"lsm_set_self_attr": {
		"unsigned int attr",
		"struct lsm_ctx *ctx",
		"u32 size",
		"u32 flags",
	},
	"fchdir": {
		"unsigned int fd",
	},
	"clock_adjtime": {
		"const clockid_t which_clock",
		"struct __kernel_timex *utx",
	},
	"open_tree_attr": {
		"int dfd",
		"const char *filename",
		"unsigned flags",
		"struct mount_attr *uattr",
		"size_t usize",
	},
	"prctl": {
		"int option",
		"unsigned long arg2",
		"unsigned long arg3",
		"unsigned long arg4",
		"unsigned long arg5",
	},
	"clock_nanosleep": {
		"const clockid_t which_clock",
		"int flags",
		"const struct __kernel_timespec *rqtp",
		"struct __kernel_timespec *rmtp",
	},
	"fanotify_mark": {
		"int fanotify_fd",
		"unsigned int flags",
		"__u64 mask",
		"int dfd",
		"const char *pathname",
	},
	"io_uring_register": {
		"unsigned int fd",
		"unsigned int opcode",
		"void *arg",
		"unsigned int nr_args",
	},
	"landlock_add_rule": {
		"const int ruleset_fd",
		"const enum landlock_rule_type rule_type",
		"const void *const rule_attr",
		"const __u32 flags",
	},
	"fgetxattr": {
		"int fd",
		"const char *name",
		"void *value",
		"size_t size",
	},
	"epoll_create": {
		"int size",
	},
	"mq_getsetattr": {
		"mqd_t mqdes",
		"const struct mq_attr *u_mqstat",
		"struct mq_attr *u_omqstat",
	},
	"fchmodat2": {
		"int dfd",
		"const char *filename",
		"umode_t mode",
		"unsigned int flags",
	},
	"getrlimit": {
		"unsigned int resource",
		"struct rlimit *rlim",
	},
	"arch_prctl": {
		"int option",
		"unsigned long arg2",
	},
	"swapon": {
		"const char *specialfile",
		"int swap_flags",
	},
	"sync_file_range": {
		"int fd",
		"loff_t offset",
		"loff_t nbytes",
		"unsigned int flags",
	},
	"getcpu": {
		"unsigned *cpup",
		"unsigned *nodep",
		"void *unused",
	},
	"landlock_create_ruleset": {
		"const struct landlock_ruleset_attr *const attr",
		"const size_t size",
		"const __u32 flags",
	},
	"set_mempolicy_home_node": {
		"unsigned long start",
		"unsigned long len",
		"unsigned long home_node",
		"unsigned long flags",
	},
	"setfsuid": {
		"uid_t uid",
	},
	"futex_requeue": {
		"struct futex_waitv *waiters",
		"unsigned int flags",
		"int nr_wake",
		"int nr_requeue",
	},
	"getcwd": {
		"char *buf",
		"unsigned long size",
	},
	"fstatfs": {
		"unsigned int fd",
		"struct statfs *buf",
	},
	"sched_setparam": {
		"pid_t pid",
		"struct sched_param *param",
	},
	"init_module": {
		"void *umod",
		"unsigned long len",
		"const char *uargs",
	},
	"tkill": {
		"pid_t pid",
		"int sig",
	},
	"sched_getaffinity": {
		"pid_t pid",
		"unsigned int len",
		"unsigned long *user_mask_ptr",
	},
	"seccomp": {
		"unsigned int op",
		"unsigned int flags",
		"void *uargs",
	},
	"madvise": {
		"unsigned long start",
		"size_t len_in",
		"int behavior",
	},
	"clock_settime": {
		"const clockid_t which_clock",
		"const struct __kernel_timespec *tp",
	},
	"epoll_pwait2": {
		"int epfd",
		"struct epoll_event *events",
		"int maxevents",
		"const struct __kernel_timespec *timeout",
		"const sigset_t *sigmask",
		"size_t sigsetsize",
	},
	"semctl": {
		"int semid",
		"int semnum",
		"int cmd",
		"unsigned long arg",
	},
	"setsid": {},
	"setgroups": {
		"int gidsetsize",
		"gid_t *grouplist",
	},
	"sigaltstack": {
		"const stack_t *uss",
		"stack_t *uoss",
	},
	"sched_get_priority_max": {
		"int policy",
	},
	"ioperm": {
		"unsigned long from",
		"unsigned long num",
		"int turn_on",
	},
	"fremovexattr": {
		"int fd",
		"const char *name",
	},
	"sched_yield": {},
	"modify_ldt": {
		"int func",
		"void *ptr",
		"unsigned long bytecount",
	},
	"iopl": {
		"unsigned int level",
	},
	"waitid": {
		"int which",
		"pid_t upid",
		"struct siginfo *infop",
		"int options",
		"struct rusage *ru",
	},
	"ioprio_set": {
		"int which",
		"int who",
		"int ioprio",
	},
	"splice": {
		"int fd_in",
		"loff_t *off_in",
		"int fd_out",
		"loff_t *off_out",
		"size_t len",
		"unsigned int flags",
	},
	"signalfd4": {
		"int ufd",
		"sigset_t *user_mask",
		"size_t sizemask",
		"int flags",
	},
	"pidfd_getfd": {
		"int pidfd",
		"int fd",
		"unsigned int flags",
	},
	"select": {
		"int n",
		"fd_set *inp",
		"fd_set *outp",
		"fd_set *exp",
		"struct __kernel_old_timeval *tvp",
	},
	"dup2": {
		"unsigned int oldfd",
		"unsigned int newfd",
	},
	"semop": {
		"int semid",
		"struct sembuf *tsops",
		"unsigned nsops",
	},
	"readahead": {
		"int fd",
		"loff_t offset",
		"size_t count",
	},
	"epoll_wait": {
		"int epfd",
		"struct epoll_event *events",
		"int maxevents",
		"int timeout",
	},
	"futex_wait": {
		"void *uaddr",
		"unsigned long val",
		"unsigned long mask",
		"unsigned int flags",
		"struct __kernel_timespec *timeout",
		"clockid_t clockid",
	},
	"mremap": {
		"unsigned long addr",
		"unsigned long old_len",
		"unsigned long new_len",
		"unsigned long flags",
		"unsigned long new_addr",
	},
	"msync": {
		"unsigned long start",
		"size_t len",
		"int flags",
	},
	"connect": {
		"int fd",
		"struct sockaddr *uservaddr",
		"int addrlen",
	},
	"sched_rr_get_interval": {
		"pid_t pid",
		"struct __kernel_timespec *interval",
	},
	"setrlimit": {
		"unsigned int resource",
		"struct rlimit *rlim",
	},
	"preadv2": {
		"unsigned long fd",
		"const struct iovec *vec",
		"unsigned long vlen",
		"unsigned long pos_l",
		"unsigned long pos_h",
		"rwf_t flags",
	},
	"mseal": {
		"unsigned long start",
		"size_t len",
		"unsigned long flags",
	},
	"msgsnd": {
		"int msqid",
		"struct msgbuf *msgp",
		"size_t msgsz",
		"int msgflg",
	},
	"fchown": {
		"unsigned int fd",
		"uid_t user",
		"gid_t group",
	},
	"pivot_root": {
		"const char *new_root",
		"const char *put_old",
	},
	"sched_setattr": {
		"pid_t pid",
		"struct sched_attr *uattr",
		"unsigned int flags",
	},
	"shmctl": {
		"int shmid",
		"int cmd",
		"struct shmid_ds *buf",
	},
	"sysinfo": {
		"struct sysinfo *info",
	},
	"rt_sigsuspend": {
		"sigset_t *unewset",
		"size_t sigsetsize",
	},
	"inotify_add_watch": {
		"int fd",
		"const char *pathname",
		"u32 mask",
	},
	"pidfd_send_signal": {
		"int pidfd",
		"int sig",
		"siginfo_t *info",
		"unsigned int flags",
	},
	"setpriority": {
		"int which",
		"int who",
		"int niceval",
	},
	"restart_syscall": {},
	"timer_settime": {
		"timer_t timer_id",
		"int flags",
		"const struct __kernel_itimerspec *new_setting",
		"struct __kernel_itimerspec *old_setting",
	},
	"set_robust_list": {
		"struct robust_list_head *head",
		"size_t len",
	},
	"epoll_pwait": {
		"int epfd",
		"struct epoll_event *events",
		"int maxevents",
		"int timeout",
		"const sigset_t *sigmask",
		"size_t sigsetsize",
	},
	"pkey_free": {
		"int pkey",
	},
	"lsetxattr": {
		"const char *pathname",
		"const char *name",
		"const void *value",
		"size_t size",
		"int flags",
	},
	"futimesat": {
		"int dfd",
		"const char *filename",
		"struct __kernel_old_timeval *utimes",
	},
	"access": {
		"const char *filename",
		"int mode",
	},
	"socketpair": {
		"int family",
		"int type",
		"int protocol",
		"int *usockvec",
	},
	"settimeofday": {
		"struct __kernel_old_timeval *tv",
		"struct timezone *tz",
	},
	"recvmmsg": {
		"int fd",
		"struct mmsghdr *mmsg",
		"unsigned int vlen",
		"unsigned int flags",
		"struct __kernel_timespec *timeout",
	},
	"syncfs": {
		"int fd",
	},
	"renameat2": {
		"int olddfd",
		"const char *oldname",
		"int newdfd",
		"const char *newname",
		"unsigned int flags",
	},
	"mq_unlink": {
		"const char *u_name",
	},
	"fchownat": {
		"int dfd",
		"const char *filename",
		"uid_t user",
		"gid_t group",
		"int flag",
	},
	"fchmodat": {
		"int dfd",
		"const char *filename",
		"umode_t mode",
	},
	"landlock_restrict_self": {
		"const int ruleset_fd",
		"const __u32 flags",
	},
	"lsm_get_self_attr": {
		"unsigned int attr",
		"struct lsm_ctx *ctx",
		"u32 *size",
		"u32 flags",
	},
	"writev": {
		"unsigned long fd",
		"const struct iovec *vec",
		"unsigned long vlen",
	},
	"fcntl": {
		"unsigned int fd",
		"unsigned int cmd",
		"unsigned long arg",
	},
	"getuid": {},
	"syslog": {
		"int type",
		"char *buf",
		"int len",
	},
	"capget": {
		"cap_user_header_t header",
		"cap_user_data_t dataptr",
	},
	"symlinkat": {
		"const char *oldname",
		"int newdfd",
		"const char *newname",
	},
	"brk": {
		"unsigned long brk",
	},
	"ioctl": {
		"unsigned int fd",
		"unsigned int cmd",
		"unsigned long arg",
	},
	"setuid": {
		"uid_t uid",
	},
	"listxattr": {
		"const char *pathname",
		"char *list",
		"size_t size",
	},
	"io_submit": {
		"aio_context_t ctx_id",
		"long nr",
		"struct iocb * *iocbpp",
	},
	"eventfd2": {
		"unsigned int count",
		"int flags",
	},
	"rt_sigaction": {
		"int sig",
		"const struct sigaction *act",
		"struct sigaction *oact",
		"size_t sigsetsize",
	},
	"rt_sigprocmask": {
		"int how",
		"sigset_t *nset",
		"sigset_t *oset",
		"size_t sigsetsize",
	},
	"pipe": {
		"int *fildes",
	},
	"getsockname": {
		"int fd",
		"struct sockaddr *usockaddr",
		"int *usockaddr_len",
	},
	"getpgid": {
		"pid_t pid",
	},
	"kexec_file_load": {
		"int kernel_fd",
		"int initrd_fd",
		"unsigned long cmdline_len",
		"const char *cmdline_ptr",
		"unsigned long flags",
	},
	"kill": {
		"pid_t pid",
		"int sig",
	},
	"move_pages": {
		"pid_t pid",
		"unsigned long nr_pages",
		"const void * *pages",
		"const int *nodes",
		"int *status",
		"int flags",
	},
	"open_tree": {
		"int dfd",
		"const char *filename",
		"unsigned flags",
	},
	"msgctl": {
		"int msqid",
		"int cmd",
		"struct msqid_ds *buf",
	},
	"utime": {
		"char *filename",
		"struct utimbuf *times",
	},
	"io_cancel": {
		"aio_context_t ctx_id",
		"struct iocb *iocb",
		"struct io_event *result",
	},
	"rseq": {
		"struct rseq *rseq",
		"u32 rseq_len",
		"int flags",
		"u32 sig",
	},
	"fchmod": {
		"unsigned int fd",
		"umode_t mode",
	},
	"setreuid": {
		"uid_t ruid",
		"uid_t euid",
	},
	"sched_getparam": {
		"pid_t pid",
		"struct sched_param *param",
	},
	"delete_module": {
		"const char *name_user",
		"unsigned int flags",
	},
	"msgrcv": {
		"int msqid",
		"struct msgbuf *msgp",
		"size_t msgsz",
		"long msgtyp",
		"int msgflg",
	},
	"removexattr": {
		"const char *pathname",
		"const char *name",
	},
	"sched_setaffinity": {
		"pid_t pid",
		"unsigned int len",
		"unsigned long *user_mask_ptr",
	},
	"mknodat": {
		"int dfd",
		"const char *filename",
		"umode_t mode",
		"unsigned int dev",
	},
	"open_by_handle_at": {
		"int mountdirfd",
		"struct file_handle *handle",
		"int flags",
	},
	"shmget": {
		"key_t key",
		"size_t size",
		"int shmflg",
	},
	"nanosleep": {
		"struct __kernel_timespec *rqtp",
		"struct __kernel_timespec *rmtp",
	},
	"setitimer": {
		"int which",
		"struct __kernel_old_itimerval *value",
		"struct __kernel_old_itimerval *ovalue",
	},
	"setsockopt": {
		"int fd",
		"int level",
		"int optname",
		"char *optval",
		"int optlen",
	},
	"execve": {
		"const char *filename",
		"const char *const *argv",
		"const char *const *envp",
	},
	"ftruncate": {
		"unsigned int fd",
		"off_t length",
	},
	"gettimeofday": {
		"struct __kernel_old_timeval *tv",
		"struct timezone *tz",
	},
	"getpriority": {
		"int which",
		"int who",
	},
	"chown": {
		"const char *filename",
		"uid_t user",
		"gid_t group",
	},
	"sched_setscheduler": {
		"pid_t pid",
		"int policy",
		"struct sched_param *param",
	},
	"munlock": {
		"unsigned long start",
		"size_t len",
	},
	"request_key": {
		"key_serial_t destringid",
	},
	"pwritev": {
		"unsigned long fd",
		"const struct iovec *vec",
		"unsigned long vlen",
		"unsigned long pos_l",
		"unsigned long pos_h",
	},
	"fsopen": {
		"unsigned int flags",
	},
	"clone3": {
		"struct clone_args *uargs",
		"size_t size",
	},
	"removexattrat": {
		"int dfd",
		"const char *pathname",
		"unsigned int at_flags",
		"const char *name",
	},
	"setns": {
		"int fd",
		"int flags",
	},
	"membarrier": {
		"int cmd",
		"unsigned int flags",
		"int cpu_id",
	},
	"poll": {
		"struct pollfd *ufds",
		"unsigned int nfds",
		"int timeout_msecs",
	},
	"accept": {
		"int fd",
		"struct sockaddr *upeer_sockaddr",
		"int *upeer_addrlen",
	},
	"chroot": {
		"const char *filename",
	},
	"timer_gettime": {
		"timer_t timer_id",
		"struct __kernel_itimerspec *setting",
	},
	"preadv": {
		"unsigned long fd",
		"const struct iovec *vec",
		"unsigned long vlen",
		"unsigned long pos_l",
		"unsigned long pos_h",
	},
	"sendmmsg": {
		"int fd",
		"struct mmsghdr *mmsg",
		"unsigned int vlen",
		"unsigned int flags",
	},
	"setgid": {
		"gid_t gid",
	},
	"gettid": {},
	"setxattr": {
		"const char *pathname",
		"const char *name",
		"const void *value",
		"size_t size",
		"int flags",
	},
	"ppoll": {
		"struct pollfd *ufds",
		"unsigned int nfds",
		"struct __kernel_timespec *tsp",
		"const sigset_t *sigmask",
		"size_t sigsetsize",
	},
	"statx": {
		"int dfd",
		"const char *filename",
		"unsigned flags",
		"unsigned int mask",
		"struct statx *buffer",
	},
	"listmount": {
		"const struct mnt_id_req *req",
		"u64 *mnt_ids",
		"size_t nr_mnt_ids",
		"unsigned int flags",
	},
	"file_getattr": {
		"int dfd",
		"const char *filename",
		"struct file_attr *ufattr",
		"size_t usize",
		"unsigned int at_flags",
	},
	"write": {
		"unsigned int fd",
		"const char *buf",
		"size_t count",
	},
	"getitimer": {
		"int which",
		"struct __kernel_old_itimerval *value",
	},
	"clone": {
		"unsigned long clone_flags",
		"unsigned long newsp",
		"int *parent_tidptr",
		"int *child_tidptr",
		"unsigned long tls",
	},
	"link": {
		"const char *oldname",
		"const char *newname",
	},
	"unshare": {
		"unsigned long unshare_flags",
	},
	"utimensat": {
		"int dfd",
		"const char *filename",
		"struct __kernel_timespec *utimes",
		"int flags",
	},
	"pkey_alloc": {
		"unsigned long flags",
		"unsigned long init_val",
	},
	"getpid": {},
	"linkat": {
		"int olddfd",
		"const char *oldname",
		"int newdfd",
		"const char *newname",
		"int flags",
	},
	"pidfd_open": {
		"pid_t pid",
		"unsigned int flags",
	},
	"process_mrelease": {
		"int pidfd",
		"unsigned int flags",
	},
	"lsm_list_modules": {
		"u64 *ids",
		"u32 *size",
		"u32 flags",
	},
	"readv": {
		"unsigned long fd",
		"const struct iovec *vec",
		"unsigned long vlen",
	},
	"alarm": {
		"unsigned int seconds",
	},
	"socket": {
		"int family",
		"int type",
		"int protocol",
	},
	"times": {
		"struct tms *tbuf",
	},
	"get_mempolicy": {
		"int *policy",
		"unsigned long *nmask",
		"unsigned long maxnode",
		"unsigned long addr",
		"unsigned long flags",
	},
	"futex_wake": {
		"void *uaddr",
		"unsigned long mask",
		"int nr",
		"unsigned int flags",
	},
	"recvmsg": {
		"int fd",
		"struct user_msghdr *msg",
		"unsigned int flags",
	},
	"fdatasync": {
		"unsigned int fd",
	},
	"setregid": {
		"gid_t rgid",
		"gid_t egid",
	},
	"fsetxattr": {
		"int fd",
		"const char *name",
		"const void *value",
		"size_t size",
		"int flags",
	},
	"flistxattr": {
		"int fd",
		"char *list",
		"size_t size",
	},
	"getxattrat": {
		"int dfd",
		"const char *pathname",
		"unsigned int at_flags",
		"const char *name",
		"struct xattr_args *uargs",
		"size_t usize",
	},
	"open": {
		"const char *filename",
		"int flags",
		"umode_t mode",
	},
	"rt_sigreturn": {},
	"mincore": {
		"unsigned long start",
		"size_t len",
		"unsigned char *vec",
	},
	"getsockopt": {
		"int fd",
		"int level",
		"int optname",
		"char *optval",
		"int *optlen",
	},
	"shmdt": {
		"char *shmaddr",
	},
	"setfsgid": {
		"gid_t gid",
	},
	"lremovexattr": {
		"const char *pathname",
		"const char *name",
	},
	"clock_getres": {
		"const clockid_t which_clock",
		"struct __kernel_timespec *tp",
	},
	"sched_getscheduler": {
		"pid_t pid",
	},
	"exit_group": {
		"int error_code",
	},
	"utimes": {
		"char *filename",
		"struct __kernel_old_timeval *utimes",
	},
	"inotify_rm_watch": {
		"int fd",
		"__s32 wd",
	},
	"faccessat": {
		"int dfd",
		"const char *filename",
		"int mode",
	},
	"pselect6": {
		"int n",
		"fd_set *inp",
		"fd_set *outp",
		"fd_set *exp",
		"struct __kernel_timespec *tsp",
		"void *sig",
	},
	"fanotify_init": {
		"unsigned int flags",
		"unsigned int event_f_flags",
	},
	"cachestat": {
		"unsigned int fd",
		"struct cachestat_range *cstat_range",
		"struct cachestat *cstat",
		"unsigned int flags",
	},
	"sysfs": {
		"int option",
		"unsigned long arg1",
		"unsigned long arg2",
	},
	"acct": {
		"const char *name",
	},
	"io_getevents": {
		"aio_context_t ctx_id",
		"long min_nr",
		"long nr",
		"struct io_event *events",
		"struct __kernel_timespec *timeout",
	},
	"remap_file_pages": {
		"unsigned long start",
		"unsigned long size",
		"unsigned long prot",
		"unsigned long pgoff",
		"unsigned long flags",
	},
	"prlimit64": {
		"pid_t pid",
		"unsigned int resource",
		"const struct rlimit64 *new_rlim",
		"struct rlimit64 *old_rlim",
	},
	"quotactl_fd": {
		"unsigned int fd",
		"unsigned int cmd",
		"qid_t id",
		"void *addr",
	},
	"wait4": {
		"pid_t upid",
		"int *stat_addr",
		"int options",
		"struct rusage *ru",
	},
	"truncate": {
		"const char *path",
		"long length",
	},
	"personality": {
		"unsigned int personality",
	},
	"ustat": {
		"unsigned dev",
		"struct ustat *ubuf",
	},
	"timer_getoverrun": {
		"timer_t timer_id",
	},
	"add_key": {
		"size_t plen",
		"key_serial_t ringid",
	},
	"io_uring_enter": {
		"unsigned int fd",
		"u32 to_submit",
		"u32 min_complete",
		"u32 flags",
		"const void *argp",
		"size_t argsz",
	},
	"getpgrp": {},
	"getdents64": {
		"unsigned int fd",
		"struct linux_dirent64 *dirent",
		"unsigned int count",
	},
	"keyctl": {
		"int option",
		"unsigned long arg2",
		"unsigned long arg3",
		"unsigned long arg4",
		"unsigned long arg5",
	},
	"process_vm_readv": {
		"pid_t pid",
		"const struct iovec *lvec",
		"unsigned long liovcnt",
		"const struct iovec *rvec",
		"unsigned long riovcnt",
		"unsigned long flags",
	},
	"pwritev2": {
		"unsigned long fd",
		"const struct iovec *vec",
		"unsigned long vlen",
		"unsigned long pos_l",
		"unsigned long pos_h",
		"rwf_t flags",
	},
	"uretprobe": {},
	"rmdir": {
		"const char *pathname",
	},
	"quotactl": {
		"unsigned int cmd",
		"const char *special",
		"qid_t id",
		"void *addr",
	},
	"munmap": {
		"unsigned long addr",
		"size_t len",
	},
	"recvfrom": {
		"int fd",
		"void *ubuf",
		"size_t size",
		"unsigned int flags",
		"struct sockaddr *addr",
		"int *addr_len",
	},
	"getrusage": {
		"int who",
		"struct rusage *ru",
	},
	"getppid": {},
	"time": {
		"__kernel_old_time_t *tloc",
	},
	"mkdirat": {
		"int dfd",
		"const char *pathname",
		"umode_t mode",
	},
	"lchown": {
		"const char *filename",
		"uid_t user",
		"gid_t group",
	},
	"munlockall": {},
	"reboot": {
		"int magic1",
		"int magic2",
		"unsigned int cmd",
		"void *arg",
	},
	"io_setup": {
		"unsigned nr_events",
		"aio_context_t *ctxp",
	},
	"copy_file_range": {
		"int fd_in",
		"loff_t *off_in",
		"int fd_out",
		"loff_t *off_out",
		"size_t len",
		"unsigned int flags",
	},
	"io_uring_setup": {
		"u32 entries",
		"struct io_uring_params *params",
	},
	"listxattrat": {
		"int dfd",
		"const char *pathname",
		"unsigned int at_flags",
		"char *list",
		"size_t size",
	},
	"getdents": {
		"unsigned int fd",
		"struct linux_dirent *dirent",
		"unsigned int count",
	},
	"getegid": {},
	"mq_notify": {
		"mqd_t mqdes",
		"const struct sigevent *u_notification",
	},
	"map_shadow_stack": {
		"unsigned long addr",
		"unsigned long size",
		"unsigned int flags",
	},
	"shmat": {
		"int shmid",
		"char *shmaddr",
		"int shmflg",
	},
	"creat": {
		"const char *pathname",
		"umode_t mode",
	},
	"geteuid": {},
	"rt_sigpending": {
		"sigset_t *uset",
		"size_t sigsetsize",
	},
	"epoll_ctl": {
		"int epfd",
		"int op",
		"int fd",
		"struct epoll_event *event",
	},
	"rt_tgsigqueueinfo": {
		"pid_t tgid",
		"pid_t pid",
		"int sig",
		"siginfo_t *uinfo",
	},
	"close_range": {
		"unsigned int fd",
		"unsigned int max_fd",
		"unsigned int flags",
	},
	"pread64": {
		"unsigned int fd",
		"char *buf",
		"size_t count",
		"loff_t pos",
	},
	"ptrace": {
		"long request",
		"long pid",
		"unsigned long addr",
		"unsigned long data",
	},
	"rt_sigtimedwait": {
		"const sigset_t *uthese",
		"siginfo_t *uinfo",
		"const struct __kernel_timespec *uts",
		"size_t sigsetsize",
	},
	"rt_sigqueueinfo": {
		"pid_t pid",
		"int sig",
		"siginfo_t *uinfo",
	},
	"sync": {},
	"getxattr": {
		"const char *pathname",
		"const char *name",
		"void *value",
		"size_t size",
	},
	"timer_delete": {
		"timer_t timer_id",
	},
	"sendto": {
		"int fd",
		"void *buff",
		"size_t len",
		"unsigned int flags",
		"struct sockaddr *addr",
		"int addr_len",
	},
	"mkdir": {
		"const char *pathname",
		"umode_t mode",
	},
	"getresgid": {
		"gid_t *rgidp",
		"gid_t *egidp",
		"gid_t *sgidp",
	},
	"statfs": {
		"const char *pathname",
		"struct statfs *buf",
	},
	"adjtimex": {
		"struct __kernel_timex *txc_p",
	},
	"mq_timedsend": {
		"mqd_t mqdes",
		"const char *u_msg_ptr",
		"size_t msg_len",
		"unsigned int msg_prio",
		"const struct __kernel_timespec *u_abs_timeout",
	},
	"inotify_init": {},
	"close": {
		"unsigned int fd",
	},
	"swapoff": {
		"const char *specialfile",
	},
	"lgetxattr": {
		"const char *pathname",
		"const char *name",
		"void *value",
		"size_t size",
	},
	"timer_create": {
		"const clockid_t which_clock",
		"struct sigevent *timer_event_spec",
		"timer_t *created_timer_id",
	},
	"mbind": {
		"unsigned long start",
		"unsigned long len",
		"unsigned long mode",
		"const unsigned long *nmask",
		"unsigned long maxnode",
		"unsigned int flags",
	},
	"ioprio_get": {
		"int which",
		"int who",
	},
	"vmsplice": {
		"int fd",
		"const struct iovec *uiov",
		"unsigned long nr_segs",
		"unsigned int flags",
	},
	"lseek": {
		"unsigned int fd",
		"off_t offset",
		"unsigned int whence",
	},
	"mmap": {
		"unsigned long addr",
		"unsigned long len",
		"unsigned long prot",
		"unsigned long flags",
		"unsigned long fd",
		"unsigned long off",
	},
	"getsid": {
		"pid_t pid",
	},
	"mknod": {
		"const char *filename",
		"umode_t mode",
		"unsigned dev",
	},
	"migrate_pages": {
		"pid_t pid",
		"unsigned long maxnode",
		"const unsigned long *old_nodes",
		"const unsigned long *new_nodes",
	},
	"shutdown": {
		"int fd",
		"int how",
	},
	"readlinkat": {
		"int dfd",
		"const char *pathname",
		"char *buf",
		"int bufsiz",
	},
	"execveat": {
		"int fd",
		"const char *filename",
		"const char *const *argv",
		"const char *const *envp",
		"int flags",
	},
	"uprobe": {},
	"move_mount": {
		"int from_dfd",
		"const char *from_pathname",
		"int to_dfd",
		"const char *to_pathname",
		"unsigned int flags",
	},
	"fsmount": {
		"int fs_fd",
		"unsigned int flags",
		"unsigned int attr_flags",
	},
	"setxattrat": {
		"int dfd",
		"const char *pathname",
		"unsigned int at_flags",
		"const char *name",
		"const struct xattr_args *uargs",
		"size_t usize",
	},
	"eventfd": {
		"unsigned int count",
	},
	"memfd_create": {
		"const char *uname",
		"unsigned int flags",
	},
	"bind": {
		"int fd",
		"struct sockaddr *umyaddr",
		"int addrlen",
	},
	"vfork": {},
	"mount": {
		"char *dev_name",
		"char *dir_name",
		"char *type",
		"unsigned long flags",
		"void *data",
	},
	"perf_event_open": {
		"struct perf_event_attr *attr_uptr",
		"pid_t pid",
		"int cpu",
		"int group_fd",
		"unsigned long flags",
	},
	"finit_module": {
		"int fd",
		"const char *uargs",
		"int flags",
	},
	"mlock2": {
		"unsigned long start",
		"size_t len",
		"int flags",
	},
	"futex_waitv": {
		"struct futex_waitv *waiters",
		"unsigned int nr_futexes",
		"unsigned int flags",
		"struct __kernel_timespec *timeout",
		"clockid_t clockid",
	},
	"read": {
		"unsigned int fd",
		"char *buf",
		"size_t count",
	},
	"getgid": {},
	"unlinkat": {
		"int dfd",
		"const char *pathname",
		"int flag",
	},
	"process_vm_writev": {
		"pid_t pid",
		"const struct iovec *lvec",
		"unsigned long liovcnt",
		"const struct iovec *rvec",
		"unsigned long riovcnt",
		"unsigned long flags",
	},
	"sched_getattr": {
		"pid_t pid",
		"struct sched_attr *uattr",
		"unsigned int usize",
		"unsigned int flags",
	},
	"fork": {},
	"symlink": {
		"const char *oldname",
		"const char *newname",
	},
	"mlockall": {
		"int flags",
	},
	"setdomainname": {
		"char *name",
		"int len",
	},
	"semtimedop": {
		"int semid",
		"struct sembuf *tsops",
		"unsigned int nsops",
		"const struct __kernel_timespec *timeout",
	},
	"renameat": {
		"int olddfd",
		"const char *oldname",
		"int newdfd",
		"const char *newname",
	},
	"epoll_create1": {
		"int flags",
	},
	"kcmp": {
		"pid_t pid1",
		"pid_t pid2",
		"int type",
		"unsigned long idx1",
		"unsigned long idx2",
	},
	"setresgid": {
		"gid_t rgid",
		"gid_t egid",
		"gid_t sgid",
	},
	"timerfd_create": {
		"int clockid",
		"int flags",
	},
	"bpf": {
		"int cmd",
		"union bpf_attr *uattr",
		"unsigned int size",
	},
	"pkey_mprotect": {
		"unsigned long start",
		"size_t len",
		"unsigned long prot",
		"int pkey",
	},
	"openat2": {
		"int dfd",
		"const char *filename",
		"struct open_how *how",
		"size_t usize",
	},
	"memfd_secret": {
		"unsigned int flags",
	},
	"statmount": {
		"const struct mnt_id_req *req",
		"struct statmount *buf",
		"size_t bufsize",
		"unsigned int flags",
	},
	"listen": {
		"int fd",
		"int backlog",
	},
	"fsync": {
		"unsigned int fd",
	},
	"llistxattr": {
		"const char *pathname",
		"char *list",
		"size_t size",
	},
	"openat": {
		"int dfd",
		"const char *filename",
		"int flags",
		"umode_t mode",
	},
	"fspick": {
		"int dfd",
		"const char *path",
		"unsigned int flags",
	},
	"listns": {
		"const struct ns_id_req *req",
		"u64 *ns_ids",
		"size_t nr_ns_ids",
		"unsigned int flags",
	},
	"getpeername": {
		"int fd",
		"struct sockaddr *usockaddr",
		"int *usockaddr_len",
	},
	"exit": {
		"int error_code",
	},
	"flock": {
		"unsigned int fd",
		"unsigned int cmd",
	},
	"rename": {
		"const char *oldname",
		"const char *newname",
	},
	"capset": {
		"cap_user_header_t header",
		"const cap_user_data_t data",
	},
}
